### PR TITLE
Increase default sky radius

### PR DESCRIPTION
**Pull request by Aceeri**
10.0 ends up giving some weird side effects sometimes.

e.g. while using bevy_rapier the debug lines cut out very close to the camera.

### CODE REVIEW

**Comment by Shatur** [comment]
But why exactly 500?

**Comment by Shatur** [comment]
Also this is the default, you can set it to whatever value you want.

**Comment by Aceeri** [comment]
No real reason for 500, but yes, I can change it to whatever I want.

I'm just putting this PR up for the sake of saving other people effort in figuring out what is going on.

**Comment by Shatur** [comment]
> 10 doesn't seem like a good default, so imo we should change it.

Agree. I would change to 100. What do you think?

**Comment by Aceeri** [comment]
100 is fine with me

**Review by Shatur — APPROVED** [review]

**Pull request merged**
