### PR TITLE
Update to Bevy 0.6

### PR DESCRIPTION
**Pull request by kbieganski**
Bevy 0.6 features a new renderer, so the changes are quite extensive. Mostly just followed the official examples for custom shaders.

In the shader, I put all the uniforms into a single bind group and separated combined fields.

I modified the system that moves the sky sphere to use `GlobalTransform`s. This is needed for cameras whose position is affected by their parents.

Also changed the way the shaders are loaded. Taken from https://github.com/ForesightMiningSoftwareCorporation/bevy_transform_gizmo/blob/main/src/gizmo_material.rs#L18

In the example, I changed the point light to a directional light.

### CODE REVIEW

**Review by Shatur — CHANGES_REQUESTED** [review]
Could you remove `.system()` from readme and from cycle.rs:13-14?
Everything else looks fine for me, the example works as expected.

**Comment by kbieganski** [comment]
> Could you remove `.system()` from readme and from cycle.rs:13-14? Everything else looks fine for me, the example works as expected.

Done

**Comment by JonahPlusPlus** [comment]
Thanks so much for doing this! I was having a lot of trouble figuring out the new rendering system with the current docs. Only change I'm making is keeping fly-cam as a `dev-dependency` (since some people may want to not use it). 

Just to clarify, `bevy_winit`, `x11`, and `bevy_gilrs` are now needed as features? I wasn't expecting the example to work without more features, but since it does, I'm just wondering if some of those features could instead be removed and just add bevy again as a `dev-dependency` (just want to avoid extra stuff). Anyways, I'll upload this. 

Thanks again; if you are interested, I can give you permissions so you can make updates as needed (or maybe I can transfer ownership to the Bevy organisation?).

**Comment by Shatur** [comment]
@[JonahPlusPlus, you are right, I removed it. And I would like to become a collaborator.

**Comment by kbieganski** [comment]
> Just to clarify, `bevy_winit`, `x11`, and `bevy_gilrs` are now needed as features?

That was a mistake on my part, I left in some stuff from earlier experimentation. But @Shatur has it covered (https://github.com/JonahPlusPlus/bevy_atmosphere/pull/5).

> Thanks again; if you are interested, I can give you permissions so you can make updates as needed

Sure :) Though I can't promise to actively update this, it's an after hours thing for me.

**Pull request merged**
