### PR TITLE
Migration bevy 0.10 -> 0.11

### PR DESCRIPTION
**Pull request by GodGotzi**
Migration from bevy 0.10 to 0.11 | mostly tested

### CODE REVIEW

**Comment by TheDan64** [comment]
@GodGotzi why was this closed?

**Comment by GodGotzi** [comment]
I dont know why but today I tried to run my fork again and it crashed all the time. I was trying to figure out why, this happens but actually has no idea. So I closed because the migration has some problems.

**Comment by GodGotzi** [comment]
What I did is vor the bevy_spectator I actually manually copied the new bevy 0.11 into atmosphere. So I rethought and ended up making a pullrequest for bevy_spectator. The bevy_spectator is only needed for examples. I believe to just wait for bevy_spectator and later update bevy_atmosphere. I did that so I can use atmosphere by myself again in 0.11, but for the pullrequest thats too dirty.

**Comment by Shatur** [comment]
@GodGotzi Maybe you could temporary open a PR with `bevy_spectator` that points to your fork? And just change it to upstream once it merged?

**Pull request closed without merging**
